### ISSUE TITLE
update to latest github-pages versions

### ISSUE THREAD

**Issue by japj** [madhur/PortableJekyll#13]
Hello,

From https://help.github.com/articles/using-jekyll-with-pages/ there is an instruction that keeps jekyll (and dependencies) up to date with the versions supported on github.

Can you update PortableJekyll to the latest 'github-pages' version?
(or is there a reason to not do this?)

**Comment by tibel** [comment]
The setup is quite easy:
https://tibel.github.io/posts/jekyll-3.0.x-portable/

Why bother with a portable package?

**Comment by madhur** [comment]
Would check on this. Thanks for update.

**Comment by purana** [comment]
@tibel Portable package does the work for you, and allows you to jump straight in producing content. I think the Portable package has a place. Sure people can choose to just do the steps you mention on your post.

**Comment by drawcard** [comment]
I need the portable package to do my work on locked down computer systems (with no admin rights) so it still has a place IMO. I do appreciate @tibel 's guide though.
