### ISSUE TITLE
No such file mentos.py

### ISSUE THREAD

**Issue by FantasyLions** [madhur/PortableJekyll#20]
![image](https://cloud.githubusercontent.com/assets/8531944/13103156/db3683ba-d58e-11e5-8d86-48a4cfdf5cda.png)
but mentos.py is existing

**Comment by madhur** [comment]
Let me check on this

**Comment by FantasyLions** [comment]
What should I do?

**Comment by madhur** [comment]
Have you downloaded this tagged release? This tagged release should work

https://github.com/madhur/PortableJekyll/releases/tag/3.1.1

**Comment by madhur** [comment]
Investigated. This happens if you are using `Pygments` as your syntax highlighter which in turn requires Python. Python has been removed from latest version. I would recommend switching the highlighter to `rogue` which is a pure ruby highlighter.

**Comment by FantasyLions** [comment]
Cool! you are awesome
