### ISSUE TITLE
Update Jekyll to 3.2.1

### ISSUE THREAD

**Issue by gethinoakes** [madhur/PortableJekyll#24]
Thanks for this awesome container.

However, Jekyll 3.2.0 is [broken on Windows](https://github.com/jekyll/jekyll/issues/5146), I've updated my local PortableJekyll to 3.2.1 but could you update this repo to 3.2.1 also?

**Comment by madhur** [comment]
Oh Ok. Thanks for informing. Let me check on this.

**Comment by gethinoakes** [comment]
Cool thanks for the quick reply :+1:

**Comment by madhur** [comment]
@gethinoakes Have updated to 3.2.1. Check.
