### ISSUE TITLE
"Jekyll is not a recognized command" Win7

### ISSUE THREAD

**Issue by Maxiride** [madhur/PortableJekyll#9]
Hello, I downloaded your package and ran the setpath.cmd file, however executing the jekyll command in cmd returns that it is an uknown command.

I guess I missed a step somewhere ^^

**Comment by Abel-Liu** [comment]
You can add PATH manual like this:
>x:\Ruby200-x64\bin;
>x:\Portable Python 2.7.5.1\App

Then edit “x:\RubyDevKit\config.yml” like this:
>\# This configuration file contains the absolute path locations of all  
>\# installed Rubies to be enhanced to work with the DevKit. This config  
>\# file is generated by the 'ruby dk.rb init' step and may be modified  
>\# before running the 'ruby dk.rb install' step. To include any installed  
>\# Rubies that were not automagically discovered, simply add a line below  
>\# the triple hyphens with the absolute path to the Ruby root directory.  
>\#  
>\# Example:  
>\#  
>\# ---  
>\# - C:/ruby19trunk  
>\# - C:/ruby192dev  
>\#  
>\---  
>\- x:/Ruby200-x64

**Comment by LoogleeTk** [comment]
Hi @Maxiride,
just open your command panel (cmd.exe) and drag the <code>setpath.cmd</code> file in your command line. You will see the directory to it, then hit enter. Nothing should happen. However, if you type <code>jekyll -v</code>, you will see that Jekyll is now installed. Easy, right?

**Comment by scorcher24** [comment]
You can also go to the Jekyll Directory, copy the file "setpath.cmd", rename it to jek.cmd.
Open it and replace all %~dp0 with the real path to your installation, e.g. "C:\PortableJekyll".

Then make a shortcut on your desktop and let it point to cmd.exe. Add /k C:\PortableJekyll.cmd" as a parameter in the shortcuts parameters. Then you have your dedicated shell for it. 

You can also add this to ConEmu if you use it.

**Comment by remidoolaeghe** [comment]
For an unknown reason, this does not work on PowerShell. But it does on command prompt.

**Comment by madhur** [comment]
because Powershell does not honour the `PATH` variable settings
